# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Filesys-DiskUsage
version:      0.04
version_from: lib/Filesys/DiskUsage.pm
installdirs:  site
requires:
    File::Basename:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
