---
abstract: 'Estimate file space usage (similar to `du`)'
author:
  - 'Jose Castro <cog@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Filesys-DiskUsage
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: '0'
  File::Find: '0'
  File::Temp: '0'
  Test::More: '0'
  Test::Warn: '0'
resources:
  repository: http://github.com/szabgab/Filesys-DiskUsage.git
version: '0.06'
